### PR TITLE
Feature/Game Logic

### PR DESCRIPTION
**Pull request by cliftondavies**
# Project: OOP
## Milestone 3: Game Logic
- [x] .gitignore
- [x] .stickler.yml
- [x] .rubocop.yml
- [x] Gemfile
- [x] lib directory with .gitkeep file
- [x] bin directory with executable main.rb file
- [x] Add Real Game Logic
- [x] Encapsulate different aspects of Game Logic in classes
- [x] Github Stickler

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Clifton!  
### Your project looks :+1: amazing!
Still, I was able to find a few bugs:
* [ ] Game declares draw too quickly in some cases:
* case one:
image
* case two:
image
* [ ] Game asks the player to enter the name but allows the name field to be empty. It's better to have some minor validation, that will not allow the player to have an empty name field:
image

* Also you have only two commits in this Pull Request. Try to make commits more often, so that your Pull Request would look more professional.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by cliftondavies** [comment]
### Hi @pelzolga123! Thanks for the review :+1: :pray:

### I have added player name validation, and fixed premature declarations of a 'draw'. :memo: 

### Happy Weekend :woman_technologist: :star:

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great work, Congratulation :+1: Project Approved.
You did all changes required previously, the game works perfectly. Go ahead and merge into development.
_Goodluck in your next milestone_ *Happy coding*

**Comment by cliftondavies** [comment]
Thanks, Olga 🙏

**Pull request merged**
