### PR TITLE
Feature/TicTacToe_Specs

### PR DESCRIPTION
**Pull request by cliftondavies**
# Project: Testing Your Ruby Code - Tic Tac Toe
## Milestones:
- [x] .gitignore
- [x] .stickler.yml
- [x] .rubocop.yml
- [x] Gemfile
- [x] Set up RSpec
- [x] Create specs for all public methods in Tic Tac Toe project
- [x] Github Stickler

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Require Changes☑️
# Hi Davies,
you have done a good job on this one🤗.
* [ ] ```attr_accessor :name``` and ```attr_reader :values, :names, :plays``` are short form of writing a public methods, so you should also test those ones as well.
* [ ] Also make sure to add negative scenario ie ```returns the names of both players``` could have a negative scenario ```does not returns the names of both players``` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))
## Kindly make these changes and submit project for review🤗
#### Happy coding 😎
Addo

**Comment by cliftondavies** [comment]
### Hi Addo. :smiley: 
### I have included specs for all accessor methods, and also tested for alternative returns from those methods with different scenarios. :memo: 
### Thanks for the review :pray:

**Review by majovanilla — APPROVED** [review]
Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
 Your tests are very well written and easy to read.

I will approve your project!!
Remember to submit the form and good luck with the next section!!

Happy coding 🤓

--Maria Reyes

**Comment by cliftondavies** [comment]
### Thanks @majovanilla 👊 🙏 ⭐ 

#### Happy Coding! 👩‍💻

**Pull request merged**
